// v6.0.1386
(function(l,g,x,D,B,v,t,y,S,M,ga,u,E,z,C,F,w,T,ha,U){function V(a,b,c){if(!a)for(a in r)return r[a];if(r[b||a])return r[b||a];var d=new ia(a);c&&d.fa();return r[b||a]=d}function W(a){for(var b in r)r[T](b)&&a(r[b])}function ra(a,b){return function(){a.call(b)}}function N(a){return"object"==typeof a}function A(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function n(a,b,c){return function(){a(b,c)}}function X(a){var b=[],c;for(c in a)a[T](c)&&a[c]!==m&&b.push(S(c)+
"="+S(a[c]));return b.join("&")}function G(a,b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),V(a,b,c||c===m);else if(/^_/.test(a))O[a]&&O[a](b,c),delete O[a];else{a=a[u](".");var e;1<a[z]&&(e=a.shift());a=a[0];var k={usecookies:1,anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11},f=function(a,b,c){e?r[e].s(a,b,c):W(function(d){d.s(a,b,c)})};if(/transaction$/i.test(a))return ta(e,
b,c,d);if("get"==a)return c=k[(b+"")[F]()]||b,e?d=r[e].g(c):W(function(a){d=a.g(c)}),d;"set"==a?(a=(b+"")[u]("."),b=a.shift(),f(k[b[F]()]||b,c,a.join("."))):"track"==a?P(Y,e,b,c,d):"event"==a?P(Z,e,b,c,d):"cancel"==a?P(function(){this.F()},e):"noCookies"==a?f(1,0):"anonymizeIP"==a?f(2,1):"tag"==a?f(3,b):"load"==a&&b&&b()}}function H(a,b){return((a>>1)+(b>>1)<<1)+(a&1)+(b&1)}function $(a,b){function c(a){return"expires="+(new v(a)).toGMTString()+";"}var d="path=/;",e=a.g(6);e&&(d+="domain="+e+";");
return{o:function(e,f){a.g(1,1)&&(g.cookie=e+"="+f+";"+c(+new v+(b?6E10:6E4))+d)},n:function(b){if(a.g(1,1))return(g.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||m},P:function(a){g.cookie=a+"=;"+c(0)+d}}}function P(a,b,c,d,e){b?a.call(r[b],c,d,e):W(function(b){a.call(b,c,d,e)})}function ia(a){var b=this;b.ka=0;var c=[];c[12]=b.b=a;b.s=function(a,d,f){if(4===a){a=b.r=b.r||{};var h={};if(!f&&!N(d))throw Error("Not an object");f?a[f]=h[f]=d:h=b.r=d;b.g(11)&&ja(b,h);c[4]=b.r}else c[a]=d};b.g=function(a,
b){return a in c?c[a]:b};var d;b.fa=function(){d=t(ra(Y,b),200)};b.F=function(){y(b.j);y(d)}}function Y(a,b,c){a&&a.call&&(c=a,a=m);b&&b.call&&(c=b,b=m);var d=this,e=ua(d,a,b),k=va(d);b=wa(d,d.i===m&&!k.I);var f=xa(),h=aa(),sa=d.g(5);y(d.j);d.m=0;d.h=0;ba(d);!d.g(9)&&e.U||e.T||x&&"preview"==x.loadPurpose||f.f.D&&f.f.w&&10>f.f.D&&10>f.f.w||(d.B=h.l,d.A=h.k,e={a:d.b,cs:f.N,cd:f.M,fl:f.S,je:f.V,la:f.W,sw:f.f.D,sh:f.f.w,dp:f.R,pu:e.ga,pt:e.ea||"-",ri:k.I,ru:k.ca,ui:b.c,re:b.da,vi:b.ia,pv:b.ba,lv:b.X,
vw:h.L,vh:h.K,dw:h.H,dh:h.G,st:h.l,sl:h.k,tv:M,un:d.g(3),pp:b.aa,cp:b.O,id:b.ha||m,ec:sa,aip:d.g(2)?1:m,tz:f.Y},d.s(11,b.c),s&&(d.uid=b.c,e.bc=1),I?(e.o_si=I,e.o_vi=ca,e.o_ci=da):d.J=1,d.$=0,Q("pv",e,function(a){a!==m&&(d.i=a,y(d.j),d.j=t(n(R,d),5E3),c&&c())},5),d.i!==m?a!==m&&(d.i=m):(t(n(ya,d),500),A(l,"beforeunload",n(za,d))))}function Z(a,b,c){b&&b.call&&(c=b,b=m);if(b===""+b||b===+b)b={caption:b};b||(b={});var d={},e;for(e in b)b[T](e)&&(d[e]=b[e]);d.gs_evt_name=a;R(this,"event",d,c)}function R(a,
b,c,d){if(a.i!==m){if(!c){var e=aa();c={vw:e.L,vh:e.K,dw:e.H,dh:e.G,st:e.l,sl:e.k,mst:a.B,msl:a.A}}c.a=a.b;c.u=a.g(11);c.id=a.g(13);c.i=a.i;c.e=b;c.tv=M;c.et=Aa(a);s&&(c.bc=1);a.J&&I&&(a.J=0,c.o_si=I,c.o_vi=ca,c.o_ci=da);Q("ping",c,function(){d&&d();y(a.j);a.j=t(n(R,a),[7E3,12E3][a.$++]||17500+5E3*B.random())},5)}else t(function(){R(a,b,c,d)},5E3)}function ja(a,b){a.i!==m?(b[C]&&(b[C]=ka(b[C][E](/^\s+|\s+$/g,"")[F]())),Q("prop",{a:a.b,u:a.g(11),p:X(b),tv:M},n,5)):t(function(){ja(a,b)},5E3)}function la(){var a=
l.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){I=a;ca=c;da=d})}function Q(a,b,c,d){var e=t(function(){f&&f();ea=(ea+1)%fa[z];b.et&&(b.et=0);b.rt=1;--d&&Q(a,b,c,d)},1E4);b.cb=Ba(function(a){c(a);f&&f();y(e)});var k=a+"?"+X(b),f;ma?ma.ja(k):f=Ca(k)}function Ca(a){var b=g[ha]("head")[0],c=g[ga]("script");c.src=(Da?"https":"http")+"://"+fa[ea]+a;b.appendChild(c);return function(){c&&b.removeChild(c);c=null}}function Ba(a){var b="_"+Ea++;O[b]=a;return b}function J(a){function b(){var a=e[w];a&&
(e[w]=a[u](c)[0])}var c=":_GS_:",d;if(J[a])return J[a];var e=l.top;J[a]=d={Q:function(){b();e[w]=(e[w]||"")+c+[a,d.c,d.C]}};try{var k=e[w]||"";if(-1!=k[U](c)){var f=k[u](c)[1][u](",");f[0]==a&&(d.c=f[1]||"",d.C=f[2]||"")}b()}catch(h){e={}}return d}function ua(a,b,c){var d=g[ga]("a");d.href=b||l.location.href;b=d.href;a.g(7,1)||(b=b[E](/\?[^#]*/,""));a.g(8)||(b=b[E](/#.*$/,""));return{ga:b,ea:c!==m?c:g.title,U:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),T:/fb_xd_(bust|fragment)/.test(b)}}function xa(){var a,
b,c,d,e,k,f=0,h=0;D&&(f=D.width,h=D.height);e=(e=l.orientation)&&(e+360)%180;return{f:{D:e?h:f,w:e?f:h},M:D&&D.colorDepth||"-",W:(x.language||x.browserLanguage||"-")[F](),V:+x.javaEnabled(),N:g.characterSet||g.charSet||"-",S:function(f,h){if(x&&(a=x.plugins)&&0<(b=a[z]))for(e=0;e<b;e++){if(-1<(d=a[e])[w][U](c=f+" "+h))return k=d.description[u](c+" "),k[1]}else if(k=l.ActiveXObject){try{if(d=(new k((c=f+h+".")+f+h)).GetVariable("$version"))return d=d[u](" ")[1][u](","),d[0]+"."+d[1]+" r"+d[2]}catch(m){}for(e=
13;--e;)try{if(d=(d=new k(c+c+e))&&1)return e+".0"}catch(g){}}return"-"}("Shockwave","Flash"),R:l.devicePixelRatio||1,Y:(new v).getTimezoneOffset()}}function aa(){function a(a){return l["inner"+a]||d&&d[e="client"+a]||c&&c[e]}function b(a){return B.max(c[e="scroll"+a]||0,d[e]||0,c[e="offset"+a],d[e],c[e="client"+a],d[e])}var c=g.body,d=g.documentElement,e;return{L:a("Width"),K:a("Height"),H:b("Width"),G:b("Height"),k:l.pageXOffset||d&&d.scrollLeft||0,l:l.pageYOffset||d&&d.scrollTop||0}}function ba(a){y(a.Z);
a.Z=t(n(na,a),15E3);a.h||(a.h=1,a.t=+new v)}function na(a){a.h&&(a.h=0,a.m=(a.m||0)+ +new v-a.t)}function Aa(a){var b=a.m,c=+new v;a.h&&(b+=c-a.t,a.t=c);a.m=0;return b}function Fa(a){ba(a);var b=aa();b.l>a.B&&(a.B=b.l);b.k>a.A&&(a.A=b.k)}function ya(a){var b=n(ba,a);A(g,"mousemove",b);A(g,"keydown",b);A(l,"scroll",n(Fa,a));A(g,"focus",b,"focusin");A(g,"blur",n(na,a),"focusout")}function va(a){a=a.g(10,g.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[E](/^.*?\/\//,
"")[U](g.domain);return{I:+(0<=b&&8>=b),ca:a}}function za(a){if(a.c!==m){var b=$(a);a.g(1,1)?b.o("gs_p_"+a.b,a.c):(b=J(a.b),b.C=a.c,b.Q())}}function wa(a,b){var c="gs_u_"+a.b,d="gs_v_"+a.b,e=$(a,1),k=J(a.b),f=(e.n(c)||k.c||"")[u](":"),h=e.n("gs_p_"+a.b)||k.C,g=1,l,p,q=a.g(11,f[0])||(g=0,0|2147483647*B.random()),r=+(f[1]||2019)+548*!!b,s=+(f[2]||4621)+379,f=(f[3]||0)/1E3,n=a.g(13),t=e.n(d);e.o(c,k.c=[q,r,s,+new v].join(":"));t&&!n&&a.s(13,n=t);n||(n=a.g(3));n&&e.o(d,n);h!==m&&(l=h,e.P("gs_p_"+a.b));
a.i!==m&&(l=a.i);(c=a.r)&&"object"==typeof c&&(c[C]&&(c[C]=ka(c[C][E](/^\s+|\s+$/g,"")[F]())),p=X(c));return{c:+q,ha:n,ia:(r-2019)/548,ba:(s-4621)/379,X:~~f,da:g,aa:l,O:p}}function ta(a,b,c,d){function e(a,b){b=b||(N(a)?a:{});N(a)||(b[w]=a);if(!b[w])throw Error("No Name");h.push(b);return g}function k(a){for(var b=0;b<a[z];)e(a[b++]);return g}function f(){P(function(){var a=$(this,1),d="gs_t_"+this.b,e=a.n(d)||0;a.o(d,+new v);Z.call(this,"_transaction",{d:JSON.stringify({id:b,pt:{ts:+e},i:h,d:c})})},
a)}!c&&N(b)&&(c=b,b=c.id);if(!b)throw Error("No ID");var h=[];d&&k(d);c&&c.track&&f();var g={id:b,addItem:e,addItems:k,track:f};return g}var m,K,p=l._gs||(K=1,function(){oa.push(arguments)}),oa=p.q=p.q||[];if(!p.v){var r={},s=l.GoSquared;if(s){var q,L;for(q in s)L=s[q],"acct"==q?(V(L,"_default",1),p(function(){function a(a){b[a.shift()].apply(b,a)}var b=s.DefaultTracker=r._default;if(q=s.q)for(;L=q.shift();)a(L);s.q={push:a};(q=s.load)&&q(b)})):"load"!=q&&"q"!=q&&p("set",q,L);q=ia.prototype;q.TrackView=
Y;q.TrackEvent=Z;q.Cancel=function(){this.F()};s.Tracker=V;s.Cancel=n(G,"cancel")}for(var pa=[],p=0;64>p;)pa[p]=0|4294967296*B.abs(B.sin(++p));var ka=function(a){var b,c,d,e,k=[];a=unescape(S(a));for(var f=a[z],h=[b=1732584193,c=-271733879,~b,~c],g=0;g<=f;)k[g>>2]|=(a.charCodeAt(g)||128)<<8*(g++%4);k[a=16*(f+8>>6)+14]=8*f;for(g=0;g<a;g+=16){f=h;for(e=0;64>e;)f=[d=f[3],H(b=f[1],(d=H(H(f[0],[b&(c=f[2])|~b&d,d&b|~d&c,b^c^d,c^(b|~d)][f=e>>4]),H(pa[e],k[[e,5*e+1,3*e+5,7*e][f]%16+g])))<<(f=[7,12,17,22,
5,9,14,20,4,11,16,23,6,10,15,21][4*f+e++%4])|d>>>32-f),b,c];for(e=4;e;)h[--e]=H(h[e],f[e])}for(a="";32>e;)a+=(h[e>>3]>>4*(1^e++&7)&15).toString(16);return a},I,ca,da,fa=["data.gosquared.com/","data2.gosquared.com/"],ea=0|B.random()*fa[z],Da=/^https:/.test(l.location),ma,O={},Ea=0;l._gs=G;for(G.v=M;p=oa.shift();)G.apply({},p);if(K){K=g[ha]("script");for(var p=K[z],qa;p--;)(qa=K[p].getAttribute("data-gs"))&&G(qa)}la();A(l,"load",la)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,
encodeURIComponent,"6.0.1386","createElement","split","replace","length","gravatar","toLowerCase","name","hasOwnProperty","getElementsByTagName","indexOf");
